[project]
name = 'evolution_of_exchange'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.evolution_of_exchange]
path = 'contracts/evolution_of_exchange.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
